---
output:
  pdf_document:
    includes:
      in_header: header.tex
    fig_width: 25
    fig_height: 25
classoption: landscape
geometry: margin=2cm
params:
  pc: 0.8
  dpc: 0.98
  hFiles: NA
  sFiles: NA
  hNames: //iso19prod/IntelligentCombine/HA/ISE/reports/data/sfcVarMapping.csv
  file1: //iso19prod/IntelligentCombine/HA/ISE/reports/data/results/Kuhburg/020-1_KUHBURG_WW-1Z0S685AKFM094700-HA.csv
  file2: //iso19prod/IntelligentCombine/HA/ISE/reports/data/results/Kuhburg/020-1_KUHBURG_WW-1Z0S685AAFM094704-HA.csv
  file3: //iso19prod/IntelligentCombine/HA/ISE/reports/data/results/Kuhburg/020-1_KUHBURG_WW-1Z0S685AVFM094684-HA.csv
  path: '~/GitHub/SimToolChain/Merge/Kuhburg/WholeField/'
  file4: 020-1_KUHBURG_WW-1Z0S685AKFM094700_MPC_EP90_PerfectPredictions_min-sim_processed.csv
  file5: 020-1_KUHBURG_WW-1Z0S685AAFM094704_MPC_EP90_PerfectPredictions_min-sim_processed.csv
  file6: 020-1_KUHBURG_WW-1Z0S685AVFM094684_MPC_EP90_PerfectPredictions_min-sim_processed.csv
  file7: //iso19prod/IntelligentCombine/HA/ISE/reports/data/sfcVarMapping.csv
  tz: "Canada/Central"
---

```{r, comment=NA, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(comment=NA, echo=FALSE, warning=FALSE, message=FALSE)
library(tidyverse)
library(dbplyr)
library(tinytex)
library(colorRamps)
library(knitr)
library(kableExtra)
library(gridExtra)
library(grid)
library(ggplot2)
library(ggmap)
library(ggpubr)
library(scales)
library(data.table)
library(pander)

source("src/versatility.R")
source("src/plotUtil.R")
source("src/tableUtil.R")

```
```{r, comment=NA, echo=FALSE, warning=FALSE, message=FALSE, }
# # Read in Files
# 
# harvFiles <- params$hFiles
# i <- 1
# asHarvest <- read.csv(paste(harvFiles$path[i]), header = TRUE, as.is = TRUE)
# i <- i+1
# while(i <= length(harvFiles$path)){
#   asHarvest <- rbind(asHarvest, read.csv(paste(harvFiles$path[i]), header = TRUE, as.is = TRUE))
#   i <- i+1
# }
# 
# simFiles <- params$sFiles
# i <- 1
# simulatedHarvest <- read.csv(paste(simFiles$path[i]), header = FALSE, as.is = TRUE)
# i <- i+1
# while(i <= length(simFiles$path)){
#   simulatedHarvest <- rbind(simulatedHarvest, read.csv(paste(simFiles$path[i]), header = FALSE, as.is = TRUE))
#   i <- i+1
# }
# remove(i)
# 
# headerNames      <- read.csv(params$hNames, header = TRUE)
# names(simulatedHarvest) <- headerNames$AWS
# 
# asHarvest        <- mutate(asHarvest, Source = "As Harvested")
# simulatedHarvest <- mutate(simulatedHarvest, Source = "Simulated")
# 
# asHarvest$hwu <- with(asHarvest, ifelse(is.na(hwu), hwi, hwu))
# asHarvest[["time"]] <- NULL
# asHarvest[["Index"]] <- NULL
# bindedDF  <- rbind(asHarvest, simulatedHarvest)
```

```{r, comment=NA, echo=FALSE, warning=FALSE, message=FALSE, }
# Read in files
setwd(params$path)
asHarvest        <- read.csv(params$file1, header = TRUE, as.is = TRUE)
asHarvest        <- rbind(asHarvest, read.csv(params$file2, header = TRUE, as.is = TRUE))
asHarvest        <- rbind(asHarvest, read.csv(params$file3, header = TRUE, as.is = TRUE))
simulatedHarvest <- read.csv(params$file4, header = FALSE, as.is = TRUE)
simulatedHarvest <- rbind(simulatedHarvest, read.csv(params$file5, header = FALSE, as.is = TRUE))
simulatedHarvest <- rbind(simulatedHarvest, read.csv(params$file6, header = FALSE, as.is = TRUE))

headerNames      <- read.csv(params$file7, header = TRUE)
names(simulatedHarvest) <- headerNames$AWS


asHarvest        <- mutate(asHarvest, Source = "As Harvested")
simulatedHarvest <- mutate(simulatedHarvest, Source = "Simulated")
asHarvest[["time"]] <- NULL
asHarvest[["Index"]] <- NULL

# tidy the data before merging

asHarvest$hwu <- with(asHarvest, ifelse(is.na(hwu), hwi, hwu))


bindedDF  <- rbind(asHarvest, simulatedHarvest)
```

# Case Report for machine `r unique(bindedDF$serialnumber)`

```{r}

model <- bindedDF$serialnumber %>% unique(.) %>% substr(., 4, 7) %>% unique(.)

maxPower <- case_when(
  model == "S660" ~ 249,
  model == "S670" ~ 292,
  model == "S680" ~ 353,
  model == "S685" ~ 373,
  model == "S690" ~ 405,
  TRUE ~ as.numeric(NA)
)

bindedDF <- bindedDF %>%
  mutate(., pu = ep/maxPower * 100)
```



```{r}
bindedDF <- bindedDF %>% dplyr::filter(., ms == 4 | ms == 5)
```

```{r}
# Prepare separate dfs for plots
simDF <- bindedDF %>% dplyr::filter(Source == "Simulated")
harvDF <- bindedDF %>% dplyr::filter(Source == "As Harvested")



```

```{r}
# Convert GPS time to field time to prepare for Versatility Calculations

harvDF$DateTime <- with(harvDF,
  .POSIXct(ISOdatetime(gpsy, gpsm, gpsd, gpsh, gpsmi, gpss, tz = "UTC"), tz = params$tz)
)

simDF$DateTime <- with(simDF,
  .POSIXct(ISOdatetime(gpsy, gpsm, gpsd, gpsh, gpsmi, gpss, tz = "UTC"), tz = params$tz)
)


harvDF$dateCode <-  strftime(harvDF$DateTime, format = "%Y-%m-%d" )
simDF$dateCode <-  strftime(simDF$DateTime, format = "%Y-%m-%d" )
```


```{r title, results='asis', fig.width=8, fig.height=3}
# The following are versatility table output and time vs metric plotting
# The for-loops are used to create versatility pages for each unique date

for( i in unique(harvDF$dateCode)){
  cat("\\pagebreak")
  
  VersDF <- harvDF %>% 
    dplyr::filter(., dateCode == i)
  VersDF$time <- VersDF$DateTime
  VersDF$model_year <- substr(VersDF$serialnumber, 10, 10)
  VersDF$model <- VersDF$serialnumber %>% substr(., 4, 7)
  VersDF$machine_name <- VersDF$serialnumber
  
  p1 <- ggplot(VersDF, aes(x = DateTime, y = pro, colour = serialnumber)) +
    geom_smooth( method = "loess", method.args = list(degree = 2), size = 1.75, se = FALSE, span = 0.33) +
    coord_cartesian(ylim=c(0, 100) + c(0,1)) +
    timeTheme() +
    labs(x = "Time", y = "Grain Productivity, t/h")
  
  pandoc.header(paste("As Harvest Grain Productivity", i, sep = " "), level=2)
  
  vtab <- get_versatility_tbl(unique(bindedDF$field)[1], "pro", VersDF)
  
  print(p1)
  
  cat(vtab[1], "\n")
  cat(vtab[2], "\n")
  
  
  cat("\\pagebreak")
  
  VersDF <- simDF %>% 
    dplyr::filter(., dateCode == i)
  VersDF$time <- VersDF$DateTime
  VersDF$model_year <- substr(VersDF$serialnumber, 10, 10)
  VersDF$model <- VersDF$serialnumber %>% substr(., 4, 7)
  VersDF$machine_name <- VersDF$serialnumber
  
  p1 <- ggplot(VersDF, aes(x = DateTime, y = pro, colour = serialnumber)) +
    geom_smooth( method = "loess", method.args = list(degree = 2), size = 1.75, se = FALSE, span = 0.33) +
    coord_cartesian(ylim=c(0, 100) + c(0,1)) +
    timeTheme() +
    labs(x = "Time", y = "Grain Productivity, t/h")
  
  pandoc.header(paste("Simulated Grain Productivity", i, sep = " "), level=2)
  
  vtab <- get_versatility_tbl(unique(bindedDF$field)[1], "pro", VersDF)
  
  print(p1)
  
  cat(vtab[1], "\n")
  cat(vtab[2], "\n")
  
  
}



for( i in unique(harvDF$dateCode)){
  cat("\\pagebreak")

  VersDF <- harvDF %>%
    dplyr::filter(., dateCode == i)
  VersDF$time <- VersDF$DateTime
  VersDF$model_year <- substr(VersDF$serialnumber, 10, 10)
  VersDF$model <- VersDF$serialnumber %>% substr(., 4, 7)
  VersDF$machine_name <- VersDF$serialnumber

  p1 <- ggplot(VersDF, aes(x = DateTime, y = gpscore, colour = serialnumber)) +
    geom_smooth( method = "loess", method.args = list(degree = 2), size = 1.75, se = FALSE, span = 0.33) +
    coord_cartesian(ylim=c(0, 100) + c(0,1)) +
    timeTheme() +
    labs(x = "Time", y = "Grain Productivity Score")
  pandoc.header(paste("As Harvest Grain Productivity Score", i, sep = " "), level=2)
  vtab <- get_versatility_tbl(unique(bindedDF$field)[1], "gpscore", VersDF)

  print(p1)

  cat(vtab[1], "\n")
  cat(vtab[2], "\n")


  cat("\\pagebreak")

  VersDF <- simDF %>%
    dplyr::filter(., dateCode == i)
  VersDF$time <- VersDF$DateTime
  VersDF$model_year <- substr(VersDF$serialnumber, 10, 10)
  VersDF$model <- VersDF$serialnumber %>% substr(., 4, 7)
  VersDF$machine_name <- VersDF$serialnumber

  p1 <- ggplot(VersDF, aes(x = DateTime, y = gpscore, colour = serialnumber)) +
    geom_smooth( method = "loess", method.args = list(degree = 2), size = 1.75, se = FALSE, span = 0.33) +
    coord_cartesian(ylim=c(0, 100) + c(0,1)) +
    timeTheme() +
    labs(x = "Time", y = "Grain Productivity Score")
  pandoc.header(paste("Simulated Grain Productivity Score", i, sep = " "), level=2)
  vtab <- get_versatility_tbl(unique(bindedDF$field)[1], "gpscore", VersDF)

  print(p1)

  cat(vtab[1], "\n")
  cat(vtab[2], "\n")

}
```




